version: "3"

services:
    mbtileserver:
        image: consbio/mbtileserver:latest
        container_name: mbtileserver
        entrypoint: /mbtileserver --enable-reload-signal
        restart: always
        ports:
            - 8000:8000
        volumes:
            - ./mbtiles/testdata:/tilesets
